### ISSUE TITLE
Azure Learn - DevOps Exercise - Include variable group

### ISSUE THREAD

**Issue by fonsecamar** [MicrosoftDocs/Contribute#400]
In the [Exercise - Run load tests in Azure Pipelines](https://docs.microsoft.com/en-us/learn/modules/run-non-functional-tests-azure-pipelines/5-run-load-tests) - section **Modify the pipeline configuration**, I think the code highlighted should add the variables group _Release_, otherwise we get a _"variable STAGING_HOSTNAME not found"_ error during the tests. The following images, Summary execution and Average response time also shows zero time for execution and response time perhaps due to the same issue. Sample as following.

```
- job: RunLoadTests
  dependsOn: Deploy
  displayName: 'Run load tests'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
  - group: Release
  - name: jmeterVersion
    value: '5.2'
  steps: 
  - script: |
      wget -c ftp.ps.pl/pub/apache/jmeter/binaries/apache-jmeter-$(jmeterVersion).tgz
      tar -xf apache-jmeter-$(jmeterVersion).tgz
    displayName: 'Install Apache JMeter'
  - script: apache-jmeter-$(jmeterVersion)/bin/./jmeter -n -t LoadTest.jmx -o Results.xml -Jhostname=$(STAGING_HOSTNAME)
    displayName: 'Run Load tests'
  - script: |
      sudo apt-get update
      sudo apt-get install xsltproc
      xsltproc JMeter2JUnit.xsl Results.xml > JUnit.xml
    displayName: 'Transform JMeter output to JUnit'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: JUnit.xml
```
